version: 2.1
orbs:
  node: circleci/node@4.1.1
jobs:
  sanity_check:
    executor:
      name: node/default
      tag: "12.20.2"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Lint Checks
          command: npm run lint
      - run:
          name: Run Tests
          command: npm run test
      - run:
          name: Build Check
          command: yarn run build
workflows:
  app_check:
    jobs:
      - sanity_check